INSERT INTO customers.customer (firstName, lastName, email)
VALUES
('Alice', 'Johnson', 'alice.johnson@example.com'),
    ('Bob', 'Smith', 'bob.smith@example.com'),
    ('Charlie', 'Brown', 'charlie.brown@example.com'), 
    ('David', 'Lee', 'david.lee@example.com'),
    ('Emily', 'Wilson', 'emily.wilson@example.com'),
    ('Frank', 'Taylor', 'frank.taylor@example.com'),
    ('Grace', 'Anderson', 'grace.anderson@example.com'),
    ('Henry', 'Harris', 'henry.harris@example.com'),
    ('Isabella', 'Clark', 'isabella.clark@example.com'),
    ('Jack', 'Lewis', 'jack.lewis@example.com'),
    ('Karen', 'Hall', 'karen.hall@example.com'),
    ('Larry', 'Allen', 'larry.allen@example.com'),
    ('Michelle', 'Young', 'michelle.young@example.com'),
    ('Nathan', 'King', 'nathan.king@example.com'),
    ('Olivia', 'Wright', 'olivia.wright@example.com'),
    ('Peter', 'Hill', 'peter.hill@example.com'),
    ('Quinn', 'Moore', 'quinn.moore@example.com'),
    ('Riley', 'Green', 'riley.green@example.com'),
    ('Sophia', 'Baker', 'sophia.baker@example.com'),
    ('Thomas', 'Nelson', 'thomas.nelson@example.com');
